### PR TITLE
Text_To_Speech_Converter/30_Days_Of_Javascript 

### PR DESCRIPTION
**Pull request by Piyushkharapkar**
I have created a small project called Text to Speech Converter using HTML, CSS, and JavaScript. This project allows users to input text into a textbox and convert it into speech. Additionally, it features different voices for the speech output.

Text to speech converter

### CODE REVIEW

**Review by Walayhs — CHANGES_REQUESTED** [review]
I have found an additional project in the commits of this pr.
### Please include readme.md of the same...

**Comment by Piyushkharapkar** [comment]
No need of readme in this

**Comment by Walayhs** [comment]
Readme file is required when adding new project..

**Comment by Walayhs** [comment]
Do check your commits in PR

**Comment by Walayhs** [comment]
Tip: If you are required to create 2 PR try creating a new branch in your fork and then commit your project to that branch. This will allow you to create a new PR for your project.

**Pull request closed without merging**
