### PR TITLE
Blog Application/30_Days_of_JavaScript#146

### PR DESCRIPTION
**Pull request by Bharat00007**
Developed a real time Blog Application #146

The Blog App is a platform where users can create, edit, and delete blogs easily. Users can add images, categorize their posts, and manage their blog content with an interactive and user-friendly interface. Whether you're sharing stories, insights, or tutorials, this app provides a seamless blogging experience.

Key Features
Create Blogs: Add new blog posts with titles, descriptions, images, and categories.
Edit Blogs: Modify existing blog entries to update content.
Delete Blogs: Remove blog posts that are no longer needed.
View Blogs: Open blogs in a modal to read full content.
Code Overview
HTML Structure: The interface is built using a combination of HTML elements to create blog cards that display title, description, image, and category.
Local Storage Integration: The app saves all blog data in the browser's local storage, allowing for persistent data across sessions.
JavaScript Functionality:
newCard: Creates the HTML structure for a new blog card.
loadData: Loads existing blogs from local storage and displays them.
updateLocalStorage: Updates the local storage whenever changes are made.
saveChanges: Saves a new blog entry and updates the display.
deleteCard: Removes a blog entry from both the display and local storage.
editCard: Allows users to edit an existing blog entry.
saveEditChanges: Saves the changes made to a blog entry.
openBlog: Opens a blog entry in a modal for detailed viewing.
This app provides a simple and efficient way to manage and share your blogs. Explore the current version to start creating and sharing your stories today!

ss1

### CODE REVIEW

**Review by animex007 — CHANGES_REQUESTED** [review]
**added 2 projects under diffrent names!**
# readme.md file is missing 

*If you have any issues please read contributor .md*

Happy coding🥳🤖

**Comment by animex007** [comment]
# Link the Issue NO.

**Comment by Bharat00007** [comment]
Readme File se ky hone val hai ??

**Comment by Bharat00007** [comment]
Added a Readme File

**Review by Walayhs — COMMENTED** [review]
Your PR has been reviewed and merged successfully.

**Comment by Walayhs** [comment]
Change the Issue number as it is not correct. I have closed the issue #147 regarding this pr.

**Pull request merged**
