### PR TITLE
BMI_calculator/Valid_Input/30_Days_of_Python#156

### PR DESCRIPTION
**Pull request by pratikshabhujade**
Added Input Validation for BMI(Body Mass Index) Calculator to Prevent Negative Values.

Fixes:#156
The validation ensures that both weight and height inputs are positive numeric values before proceeding with the BMI calculation.
Screenshot 2024-07-25 011534

### CODE REVIEW

**Review by Axwell-2 — CHANGES_REQUESTED** [review]
For Currency Exchange 
1.Redundant API Key Assignment
The first assignment is unnecessary since it is immediately overwritten by the second please update it 
2.Duplicate API Request
The first request is redundant because you don't use its response before making the second request.The code following the first API request is executed twice because of the duplicate request
If 'to_currency' is not present in the 'conversion_rates,' this will raise a 'KeyError'

**Review by Axwell-2 — CHANGES_REQUESTED** [review]
In the initial inputs for 'weight' and 'height' in BMI calculator as they are not needed before the get_positive_number function calls.

**Comment by Axwell-2** [comment]
Please Review Your codes

**Comment by pratikshabhujade** [comment]
> For BMI calculator In the initial inputs for 'weight' and 'height' in BMI calculator as they are not needed before the get_positive_number function calls.


To avoid getting input before calling the get_positive_number function, should I avoid using intermediate variables like weight and height? Would it be better to call get_positive_number directly within the calculate_bmi function call to streamline the process?

**Review by Axwell-2 — COMMENTED** [review]
Updation Needed

**Pull request closed without merging**
