### PR TITLE
30_days_of _python/ Hangman Game  

### PR DESCRIPTION
**Pull request by rohansnishad**
# Description #19 
This PR adds a new Python-based Hangman Game. This interactive game lets players test their vocabulary and deduction skills as they try to uncover a hidden word, one letter at a time. With each incorrect guess, a part of the hangman figure is drawn, bringing the player closer to defeat.

## Features
- Simple and intuitive command-line interface for easy interaction.
- Easily add or modify the list of words for endless variety.
- Keep track of wins and losses to monitor your progress.
- Runs smoothly on various operating systems with Python installed.

### CODE REVIEW

**Review by jitacm — APPROVED** [review]

**Comment by jitacm** [comment]
plz resolve the conflict !

**Comment by animex007** [comment]
@rohansnishad pls resolve the issue ASAP! or delete this repo and reopen PR!

**Review by animex007 — CHANGES_REQUESTED** [review]
plz do the necessary changes otherwise we will delete the PR

**Comment by jitacm** [comment]
@rohansnishad  we are closing this issue!

**Pull request closed without merging**
